#!/bin/bash
### danbing-tk motif dosage pipeline
### edit by sjzhang  -- 20230413
###





#PBS -V
#PBS -j eo
#PBS -N motif_dosage
#PBS -q Blade
#PBS -l nodes=1:ppn=1
#PBS -d /home2/sjzhang/work/VNTRv2/1-motifDosage

echo Sample batch in motif dosage Start time is `date +%Y/%m/%d--%H:%M`
work_start_time=$(date +%s)

cd /home2/sjzhang/work/VNTRv2/1-motifDosage

for file in world.sam*;
do 
python slideWindowKmerGZ-1.py 38685TR_locus_motif.tsv /home2/sjzhang/git/danbing-tk/resources/danbing_1.3.1/metadata/danbing_aln_output.tr_kmers.metadata.txt $file /Parastor300s_G30S/vntr/work/danbingtk/output/world_4096_kmers/ ${file}_motif_dosage
done   

end_time=$(date +%s)
echo "#######-- Sample batch in motif dosage End Time:`date +%Y/%m/%d--%H:%M`  --#######"


